name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your build steps here, such as compiling or generating files
      - name: Generate file
        run: echo "Generated content" > generated-file.txt

      # Upload the generated file as a build artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: generated-file.txt
