name: Update Text File and Publish Release

on:
  push:
    branches:
      - main

jobs:
  update_text_file_and_publish_release:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare workspace
        run: |
          mkdir -p workspace
          cd workspace
          echo "Preparing workspace..."
      
      - name: Create text file with actual timestamp
        run: |
          cd workspace
          echo "Creating text file with actual timestamp..."
          echo $(date) > text_file.txt
      
      - name: Publish text file as artifact
        uses: actions/upload-artifact@v2
        with:
          name: text-file-artifact
          path: workspace/text_file.txt
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_PAT }} 
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          body: |
            This is an automated release created by GitHub Actions.
            Timestamp: $(date)
          draft: false
          prerelease: false



# name: Update Text File

# on:
#   push:
#     branches:
#       - main

# jobs:
#   update_text_file:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Prepare workspace
#         run: |
#           mkdir -p workspace
#           cd workspace
#           echo "Preparing workspace..."
      
#       - name: Create text file with actual timestamp
#         run: |
#           cd workspace
#           echo "Creating text file with actual timestamp..."
#           echo $(date) > text_file.txt
      
#       - name: Publish text file as artifact
#         uses: actions/upload-artifact@v2
#         with:
#           name: text-file-artifact
#           path: workspace/text_file.txt


# name: Build and Deploy

# on:
#   push:
#     branches:
#       - main

# jobs:

#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2



#       # - name: remove old
#       #   run: /home/runner/work/flutter-workspace-2/flutter-workspace-2/generated-file.txt


#       # Add your build steps here, such as compiling or generating files
#       - name: Generate file
#         run: echo "Generated content" > generated-file.txt

#       # Upload the generated file as a build artifact
#       - name: Upload artifact
#         uses: actions/upload-artifact@v2
#         with:
#           name: my-artifact
#           path: generated-file.txt


#   # create_release:
#   #   runs-on: ubuntu-latest

#   #   steps:
#   #     - name: Checkout code
#   #       uses: actions/checkout@v2

#       # Download the artifact


#       # - name: Download artifact
#       #   uses: actions/download-artifact@v2
#       #   with:
#       #     name: my-artifact
#       #     path: generated-file.txt

#       # Create a GitHub release
#       - name: Create Release
#         id: create_release
#         uses: actions/create-release@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           tag_name: v1.0.0
#           release_name: Release v1.0.0
#           body: |
#             This is a new release.
#           draft: false
#           prerelease: false
